//// Tests for RFC 5545 §3.8.5.2 RDATE (recurrence date).
////
//// RDATE specifies additional explicit recurrence instances beyond the
//// RRULE-generated set. Unlike EXDATE (which excludes), RDATE includes
//// specific dates that might not match the recurrence pattern.
////
//// Format mirrors EXDATE: comma-separated DATE values for all-day events,
//// or DATE-TIME (UTC with Z, or TZID-qualified) for timed events.

import cal.{AllDay, AtTime}
import gleam/list
import gleam/time/calendar
import gleam/time/duration
import gleam/time/timestamp
import ical

// 2-week window: Sun 2026-06-14 00:00 ET -> Sun 2026-06-28 00:00 ET
fn two_weeks() -> #(timestamp.Timestamp, timestamp.Timestamp) {
  #(
    timestamp.from_unix_seconds(1_781_409_600),
    timestamp.from_unix_seconds(1_782_619_200),
  )
}

// 4-week window: Sun 2026-06-14 00:00 ET -> Tue 2026-07-14 00:00 ET
fn four_weeks() -> #(timestamp.Timestamp, timestamp.Timestamp) {
  #(
    timestamp.from_unix_seconds(1_781_409_600),
    timestamp.from_unix_seconds(1_784_001_600),
  )
}

fn et_date(ts: timestamp.Timestamp) -> calendar.Date {
  let offset = duration.seconds(-4 * 3600)
  timestamp.to_calendar(ts, offset).0
}

fn event_dates(events: List(cal.Event)) -> List(calendar.Date) {
  list.map(events, fn(e: cal.Event) {
    case e.start {
      AtTime(ts) -> et_date(ts)
      AllDay(d) -> d
    }
  })
}

pub fn rdate_single_additional_date_test() -> Nil {
  // Weekly on Mondays, plus an extra Wednesday via RDATE.
  // Should have: Mon Jun 15, Wed Jun 17 (RDATE), Mon Jun 22.
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:rdate-basic\r\n"
    <> "SUMMARY:Weekly + Extra\r\n"
    <> "DTSTART;VALUE=DATE:20260615\r\n"
    <> "DTEND;VALUE=DATE:20260616\r\n"
    <> "RRULE:FREQ=WEEKLY;BYDAY=MO\r\n"
    <> "RDATE;VALUE=DATE:20260617\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = two_weeks()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 3
  assert list.contains(dates, calendar.Date(2026, calendar.June, 15))  // Mon
  assert list.contains(dates, calendar.Date(2026, calendar.June, 17))  // Wed (RDATE)
  assert list.contains(dates, calendar.Date(2026, calendar.June, 22))  // Mon
  Nil
}

pub fn rdate_multiple_values_test() -> Nil {
  // Daily for 3 days, plus RDATE adding two extra dates outside the pattern.
  // DTSTART=Jun 15, RRULE: daily → Jun 15,16,17,18,19,20...
  // RDATE adds: Jun 21, Jun 25
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:rdate-multi\r\n"
    <> "SUMMARY:Daily + Extras\r\n"
    <> "DTSTART;VALUE=DATE:20260615\r\n"
    <> "DTEND;VALUE=DATE:20260616\r\n"
    <> "RRULE:FREQ=DAILY;COUNT=3\r\n"
    <> "RDATE;VALUE=DATE:20260621,20260625\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = four_weeks()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 5
  assert list.contains(dates, calendar.Date(2026, calendar.June, 15))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 16))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 17))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 21))  // RDATE
  assert list.contains(dates, calendar.Date(2026, calendar.June, 25))  // RDATE
  Nil
}

pub fn rdate_timed_utc_test() -> Nil {
  // Timed event with UTC RDATE values.
  // Weekly Tuesdays at 10am, plus an extra Thursday at 2pm UTC (10am ET same day).
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:rdate-timed\r\n"
    <> "SUMMARY:Weekly Tue + Extra Thu\r\n"
    <> "DTSTART:20260616T140000Z\r\n"
    <> "DTEND:20260616T150000Z\r\n"
    <> "RRULE:FREQ=WEEKLY;BYDAY=TU\r\n"
    <> "RDATE:20260618T140000Z\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = two_weeks()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 3
  // Tue Jun 16, Thu Jun 18 (RDATE), Tue Jun 23
  assert list.contains(dates, calendar.Date(2026, calendar.June, 16))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 18))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 23))
  Nil
}

pub fn rdate_duplicates_removed_test() -> Nil {
  // RDATE can duplicate dates already generated by RRULE.
  // The spec says duplicates are removed (set semantics).
  // DTSTART=Jun 15 (Monday), RRULE: weekly on Mondays, RDATE: Jun 15, Jun 22
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:rdate-dedup\r\n"
    <> "SUMMARY:Weekly with Duplicate RDATE\r\n"
    <> "DTSTART;VALUE=DATE:20260615\r\n"
    <> "DTEND;VALUE=DATE:20260616\r\n"
    <> "RRULE:FREQ=WEEKLY;BYDAY=MO\r\n"
    <> "RDATE;VALUE=DATE:20260615,20260622\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = two_weeks()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  // Should have exactly 2 dates (Jun 15 and Jun 22), not 4
  assert list.length(dates) == 2
  assert list.contains(dates, calendar.Date(2026, calendar.June, 15))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 22))
  Nil
}

pub fn rdate_no_rrule_test() -> Nil {
  // RDATE without RRULE: just explicit recurrence dates, no generated ones.
  // This is valid per RFC 5545 (standalone RDATE).
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:rdate-only\r\n"
    <> "SUMMARY:Explicit Dates Only\r\n"
    <> "DTSTART;VALUE=DATE:20260615\r\n"
    <> "DTEND;VALUE=DATE:20260616\r\n"
    <> "RDATE;VALUE=DATE:20260617,20260619\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = two_weeks()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 3
  assert list.contains(dates, calendar.Date(2026, calendar.June, 15))  // DTSTART
  assert list.contains(dates, calendar.Date(2026, calendar.June, 17))  // RDATE
  assert list.contains(dates, calendar.Date(2026, calendar.June, 19))  // RDATE
  Nil
}

pub fn rdate_multi_property_lines_test() -> Nil {
  // Multiple RDATE properties (not comma-separated) should be merged.
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:rdate-multi-lines\r\n"
    <> "SUMMARY:Multiple RDATE lines\r\n"
    <> "DTSTART;VALUE=DATE:20260615\r\n"
    <> "DTEND;VALUE=DATE:20260616\r\n"
    <> "RDATE;VALUE=DATE:20260617\r\n"
    <> "RDATE;VALUE=DATE:20260619\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = two_weeks()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 3
  assert list.contains(dates, calendar.Date(2026, calendar.June, 15))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 17))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 19))
  Nil
}

pub fn rdate_outside_window_not_returned_test() -> Nil {
  // RDATE values outside the query window should not be returned.
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:rdate-outside\r\n"
    <> "SUMMARY:Some Inside, Some Outside\r\n"
    <> "DTSTART;VALUE=DATE:20260613\r\n"
    <> "DTEND;VALUE=DATE:20260614\r\n"
    <> "RDATE;VALUE=DATE:20260612,20260618,20260630\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = two_weeks()
  // Window: Jun 14 to Jun 28
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  // Jun 13 (DTSTART), Jun 18 (RDATE) are inside; Jun 12 and Jun 30 are outside
  assert list.length(dates) == 2
  assert list.contains(dates, calendar.Date(2026, calendar.June, 13))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 18))
  Nil
}

pub fn rdate_with_exdate_test() -> Nil {
  // RDATE and EXDATE can coexist: RDATE adds, EXDATE removes.
  // DTSTART=Jun 15 (Mon), RRULE: weekly on Mondays
  // RDATE adds: Jun 18 (Thu), EXDATE removes: Jun 15 (first occurrence)
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:rdate-exdate\r\n"
    <> "SUMMARY:RRULE + RDATE - EXDATE\r\n"
    <> "DTSTART;VALUE=DATE:20260615\r\n"
    <> "DTEND;VALUE=DATE:20260616\r\n"
    <> "RRULE:FREQ=WEEKLY;BYDAY=MO\r\n"
    <> "RDATE;VALUE=DATE:20260618\r\n"
    <> "EXDATE;VALUE=DATE:20260615\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = two_weeks()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  // RRULE generated: Jun 15, Jun 22
  // RDATE adds: Jun 18
  // EXDATE removes: Jun 15
  // Result: Jun 18, Jun 22
  assert list.length(dates) == 2
  assert !list.contains(dates, calendar.Date(2026, calendar.June, 15))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 18))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 22))
  Nil
}

pub fn rdate_timed_with_tzid_test() -> Nil {
  // RDATE with TZID parameter (America/New_York in this case).
  // Timed event at 10am ET, with RDATE at 2pm ET (same day).
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:rdate-tzid\r\n"
    <> "SUMMARY:Timed with TZID RDATE\r\n"
    <> "DTSTART;TZID=America/New_York:20260615T100000\r\n"
    <> "DTEND;TZID=America/New_York:20260615T110000\r\n"
    <> "RRULE:FREQ=DAILY;COUNT=2\r\n"
    <> "RDATE;TZID=America/New_York:20260616T140000\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = two_weeks()
  let events = ical.parse_events(ical_text, "Cal", s, e)
  let dates = event_dates(events)
  assert list.length(dates) == 3
  assert list.contains(dates, calendar.Date(2026, calendar.June, 15))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 16))  // RRULE
  // Jun 16 (RDATE) is same date as RRULE occurrence, so deduplicated
  Nil
}
