//// Tests for RFC 5545 §3.3.10 BYSETPOS recurrence rule part.
////
//// BYSETPOS specifies a list of positions (1..366 or -366..-1) that
//// select specific occurrences from the candidate set generated by other
//// BYxxx rule parts within each FREQ interval.
////
//// Per RFC 5545: "BYSETPOS rule part MUST only be used in conjunction with
//// another BYxxx rule part." When no other BY rule is present, BYSETPOS is
//// ignored. The candidate set is sorted chronologically before position
//// selection. Negative values count from the end (-1 = last).
////
//// Common patterns:
////   * Last workday of month: BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1
////   * 1st and 3rd Monday: BYDAY=MO;BYSETPOS=1,3
////   * First weekend day of month: BYDAY=SA,SU;BYSETPOS=1

import cal.{AllDay, AtTime}
import gleam/list
import gleam/time/calendar
import gleam/time/duration
import gleam/time/timestamp
import ical

// 4-month window: Mon 2026-06-01 00:00 EDT -> Thu 2026-10-01 00:00 EDT
fn four_months() -> #(timestamp.Timestamp, timestamp.Timestamp) {
  #(
    timestamp.from_unix_seconds(1_780_286_400),
    timestamp.from_unix_seconds(1_790_827_200),
  )
}

fn et_date(ts: timestamp.Timestamp) -> calendar.Date {
  let offset = duration.seconds(-4 * 3600)
  timestamp.to_calendar(ts, offset).0
}

fn event_dates(events: List(cal.Event)) -> List(calendar.Date) {
  list.map(events, fn(e: cal.Event) {
    case e.start {
      AtTime(ts) -> et_date(ts)
      AllDay(d) -> d
    }
  })
}

pub fn monthly_bysetpos_last_weekday_test() -> Nil {
  // FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1
  // Last workday of each month.
  // Jun 30 2026 = Tue, Jul 31 2026 = Fri, Aug 31 2026 = Mon, Sep 30 2026 = Wed.
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:bsp-last-weekday\r\n"
    <> "SUMMARY:Month-end report\r\n"
    <> "DTSTART;VALUE=DATE:20260630\r\n"
    <> "DTEND;VALUE=DATE:20260701\r\n"
    <> "RRULE:FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = four_months()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 4
  assert list.contains(dates, calendar.Date(2026, calendar.June, 30))
  assert list.contains(dates, calendar.Date(2026, calendar.July, 31))
  assert list.contains(dates, calendar.Date(2026, calendar.August, 31))
  assert list.contains(dates, calendar.Date(2026, calendar.September, 30))
  Nil
}

pub fn monthly_bysetpos_second_to_last_weekday_test() -> Nil {
  // FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-2
  // Second-to-last weekday of each month.
  // Jun: Mon 29 (last is Tue 30); Jul: Thu 30 (last Fri 31);
  // Aug: Fri 28 (last Mon 31); Sep: Tue 29 (last Wed 30).
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:bsp-2nd-last\r\n"
    <> "SUMMARY:Pre-close review\r\n"
    <> "DTSTART;VALUE=DATE:20260629\r\n"
    <> "DTEND;VALUE=DATE:20260630\r\n"
    <> "RRULE:FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-2\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = four_months()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 4
  assert list.contains(dates, calendar.Date(2026, calendar.June, 29))
  assert list.contains(dates, calendar.Date(2026, calendar.July, 30))
  assert list.contains(dates, calendar.Date(2026, calendar.August, 28))
  assert list.contains(dates, calendar.Date(2026, calendar.September, 29))
  Nil
}

pub fn monthly_bysetpos_multiple_positions_test() -> Nil {
  // FREQ=MONTHLY;BYDAY=MO;BYSETPOS=2,4
  // 2nd and 4th Monday of each month.
  // Jun: Mondays 1,8,15,22,29 -> 2nd=8, 4th=22.
  // Jul: 6,13,20,27 -> 2nd=13, 4th=27.
  // Aug: 3,10,17,24,31 -> 2nd=10, 4th=24.
  // Sep: 7,14,21,28 -> 2nd=14, 4th=28.
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:bsp-multi\r\n"
    <> "SUMMARY:1-on-1\r\n"
    <> "DTSTART;VALUE=DATE:20260608\r\n"
    <> "DTEND;VALUE=DATE:20260609\r\n"
    <> "RRULE:FREQ=MONTHLY;BYDAY=MO;BYSETPOS=2,4\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = four_months()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 8
  assert list.contains(dates, calendar.Date(2026, calendar.June, 8))
  assert list.contains(dates, calendar.Date(2026, calendar.June, 22))
  assert list.contains(dates, calendar.Date(2026, calendar.July, 13))
  assert list.contains(dates, calendar.Date(2026, calendar.July, 27))
  assert list.contains(dates, calendar.Date(2026, calendar.August, 10))
  assert list.contains(dates, calendar.Date(2026, calendar.August, 24))
  assert list.contains(dates, calendar.Date(2026, calendar.September, 14))
  assert list.contains(dates, calendar.Date(2026, calendar.September, 28))
  Nil
}

pub fn monthly_bysetpos_first_weekend_test() -> Nil {
  // FREQ=MONTHLY;BYDAY=SA,SU;BYSETPOS=1
  // First weekend day of each month.
  // Jun (Mon Jun 1): first Sat=Jun 6.
  // Jul (Wed Jul 1): first Sat=Jul 4.
  // Aug (Sat Aug 1): first Sat=Aug 1.
  // Sep (Tue Sep 1): first Sat=Sep 5.
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:bsp-first-weekend\r\n"
    <> "SUMMARY:Brunch\r\n"
    <> "DTSTART;VALUE=DATE:20260606\r\n"
    <> "DTEND;VALUE=DATE:20260607\r\n"
    <> "RRULE:FREQ=MONTHLY;BYDAY=SA,SU;BYSETPOS=1\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = four_months()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 4
  assert list.contains(dates, calendar.Date(2026, calendar.June, 6))
  assert list.contains(dates, calendar.Date(2026, calendar.July, 4))
  assert list.contains(dates, calendar.Date(2026, calendar.August, 1))
  assert list.contains(dates, calendar.Date(2026, calendar.September, 5))
  Nil
}

pub fn monthly_bysetpos_timed_test() -> Nil {
  // Timed variant of last-weekday: 09:00 EDT on the last workday of each month.
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:bsp-timed\r\n"
    <> "SUMMARY:Standup\r\n"
    <> "DTSTART;TZID=America/New_York:20260630T090000\r\n"
    <> "DTEND;TZID=America/New_York:20260630T093000\r\n"
    <> "RRULE:FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = four_months()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 4
  assert list.contains(dates, calendar.Date(2026, calendar.June, 30))
  assert list.contains(dates, calendar.Date(2026, calendar.July, 31))
  assert list.contains(dates, calendar.Date(2026, calendar.August, 31))
  assert list.contains(dates, calendar.Date(2026, calendar.September, 30))
  Nil
}

pub fn bysetpos_invalid_values_dropped_test() -> Nil {
  // BYSETPOS=0, 367, -367 are invalid (range is 1..366 or -366..-1).
  // BYSETPOS=-1,0,367 should be parsed as just BYSETPOS=-1.
  // Result: same as monthly_bysetpos_last_weekday_test (last workday of month).
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:bsp-invalid\r\n"
    <> "SUMMARY:End-of-month\r\n"
    <> "DTSTART;VALUE=DATE:20260630\r\n"
    <> "DTEND;VALUE=DATE:20260701\r\n"
    <> "RRULE:FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1,0,367\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = four_months()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  assert list.length(dates) == 4
  assert list.contains(dates, calendar.Date(2026, calendar.June, 30))
  assert list.contains(dates, calendar.Date(2026, calendar.July, 31))
  assert list.contains(dates, calendar.Date(2026, calendar.August, 31))
  assert list.contains(dates, calendar.Date(2026, calendar.September, 30))
  Nil
}

pub fn bysetpos_without_byrule_noop_test() -> Nil {
  // Per RFC 5545: BYSETPOS MUST be used in conjunction with another BYxxx
  // rule. When no other BY rule is present, BYSETPOS is ignored — the
  // recurrence behaves as plain FREQ.
  // FREQ=DAILY with no BY rule, BYSETPOS=1: ignore BYSETPOS, emit daily.
  // 4-month window covers ~122 days starting Jun 1 -> Sep 30 inclusive.
  let ical_text =
    "BEGIN:VCALENDAR\r\n"
    <> "VERSION:2.0\r\n"
    <> "BEGIN:VEVENT\r\n"
    <> "UID:bsp-noop\r\n"
    <> "SUMMARY:Daily\r\n"
    <> "DTSTART;VALUE=DATE:20260601\r\n"
    <> "DTEND;VALUE=DATE:20260602\r\n"
    <> "RRULE:FREQ=DAILY;BYSETPOS=1\r\n"
    <> "END:VEVENT\r\n"
    <> "END:VCALENDAR\r\n"

  let #(s, e) = four_months()
  let dates = ical.parse_events(ical_text, "Cal", s, e) |> event_dates
  // Window is Jun 1 -> Oct 1 (exclusive). Days in Jun (30) + Jul (31)
  // + Aug (31) + Sep (30) = 122 daily occurrences.
  assert list.length(dates) == 122
  assert list.contains(dates, calendar.Date(2026, calendar.June, 1))
  assert list.contains(dates, calendar.Date(2026, calendar.September, 30))
  Nil
}
